using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AbpPoc.Permissions;
using AbpPoc.PartTests;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AbpPoc.Shared;

namespace AbpPoc.PartTests
{
    public class PartTestsAppService : PartTestsAppServiceBase, IPartTestsAppService
    {
        //<suite-custom-code-autogenerated>
        public PartTestsAppService(IPartTestRepository partTestRepository, PartTestManager partTestManager, IDistributedCache<PartTestDownloadTokenCacheItem, string> downloadTokenCache)
            : base(partTestRepository, partTestManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}