using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AbpPoc.PartTests
{
    public class PartTestManager : PartTestManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PartTestManager(IPartTestRepository partTestRepository)
            : base(partTestRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}