using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AbpPoc.Parts
{
    public class PartManager : PartManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PartManager(IPartRepository partRepository)
            : base(partRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}