using AbpPoc.Parts;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace AbpPoc.Ipbs
{
    public class Ipb : IpbBase
    {
        //<suite-custom-code-autogenerated>
        protected Ipb()
        {

        }

        public Ipb(Guid id, Guid? sourcePart, Guid? relatedPart, string ipbIndex, string figureName, string figureNumber, string sourceId, string relatedId, string? toNumber = null, string? indentureLevel = null)
            : base(id, sourcePart, relatedPart, ipbIndex, figureName, figureNumber, sourceId, relatedId, toNumber, indentureLevel)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}