using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AbpPoc.Ipbs
{
    public class IpbManager : IpbManagerBase
    {
        //<suite-custom-code-autogenerated>
        public IpbManager(IIpbRepository ipbRepository)
            : base(ipbRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}