using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace AbpPoc.Documents
{
    public class DocumentManager : DocumentManagerBase
    {
        //<suite-custom-code-autogenerated>
        public DocumentManager(IDocumentRepository documentRepository)
            : base(documentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}