using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using AbpPoc.Permissions;
using AbpPoc.Parts;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using AbpPoc.Shared;

namespace AbpPoc.Parts
{
    public class PartsAppService : PartsAppServiceBase, IPartsAppService
    {
        //<suite-custom-code-autogenerated>
        public PartsAppService(IPartRepository partRepository, PartManager partManager, IDistributedCache<PartDownloadTokenCacheItem, string> downloadTokenCache)
            : base(partRepository, partManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}